'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GamePlayerStat
    Public Property gameid As Integer
    Public Property username As String
    Public Property char_name As String
    Public Property xypoint As String
    Public Property score As Nullable(Of Integer)

End Class
