'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class player
    Public Property userid As Integer
    Public Property username As String
    Public Property passwrd As String
    Public Property admin As String
    Public Property attempts As Nullable(Of Integer)
    Public Property locked As String
    Public Property highscore As Nullable(Of Integer)
    Public Property isonline As String
    Public Property lastlogin As Date

End Class
